In [1]:
import numpy as np

In [3]:
redwine = np.loadtxt(fname='c:/hrim/winequality-red.csv',delimiter=';',skiprows=1) #skiprows => 첫줄에 column명이 있어서 그거 skip
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [4]:
redwine.sum() #전체의 sum

152084.78194

In [5]:
redwine.sum(axis=0) # 열별로 더한것들

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [6]:
redwine.sum(axis=1) #행별로 더한것들

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

In [7]:
redwine.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [8]:
redwine[:,0].mean()

8.31963727329581