In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#numpy에서 제공하는 array 생성
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
np.zeros((3,3)) #3행3열 0으로 초기화 한 배열 만들어줌

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,2)) #1로 초기화시켜줌

array([[1., 1.],
       [1., 1.]])

In [8]:
np.empty((4,4)) #배열만 만듦. 값초기화되어있지안않음(null과는 다름)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.39784051e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
arr=np.array([[1,2,3],[4,5,6]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr.shape 

(2, 3)

In [15]:
arr.ndim #2개의 축으로 구성

2

In [16]:
arr.dtype

dtype('int32')

In [18]:
def ppr(arr):
    print("type:{}".format(type(arr)))
    print("shape:{},dim:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("arr data: \n", arr)

In [19]:
ppr(arr)

type:<class 'numpy.ndarray'>
shape:(2, 3),dim:2,dtype:int32
arr data: 
 [[1 2 3]
 [4 5 6]]


In [22]:
np.arange(1,7).reshape(2,3) #np.arange값을 형변환 (2,3)으로

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.arange(1,7).reshape(-1,3) # -1: 나머지는 알아서 계산해줘 해도 같은결과 얻음

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.arange(1,7).reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a1 = np.arange(1,7)
a2 = np.arange(1,7).reshape(-1,3) #(a.b)=> a나 b를 축으로 생각할것
a3 = np.arange(1,25).reshape(2,3,4) #reshape(2,3,-1) 줘도 똑같이 계산됨 

In [29]:
ppr(a1)

type:<class 'numpy.ndarray'>
shape:(6,),dim:1,dtype:int32
arr data: 
 [1 2 3 4 5 6]


In [30]:
ppr(a2) #2차원

type:<class 'numpy.ndarray'>
shape:(2, 3),dim:2,dtype:int32
arr data: 
 [[1 2 3]
 [4 5 6]]


In [31]:
ppr(a3) #3차원

type:<class 'numpy.ndarray'>
shape:(2, 3, 4),dim:3,dtype:int32
arr data: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [32]:
a4=np.arange(1,49).reshape(2,2,3,4) #4개짜리가 3개씩있고 그런게 2개씩있고 그런 덩어리가 또 2개인것
ppr(a4)

type:<class 'numpy.ndarray'>
shape:(2, 2, 3, 4),dim:4,dtype:int32
arr data: 
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]


In [33]:
arr_int = np.arange(1,5)
arr_int.dtype

dtype('int32')

In [35]:
arr_int.astype(np.float64) #자동으로 float형으로 바꿔줌.

array([1., 2., 3., 4.])

In [36]:
arr_float = arr_int.astype(np.float64) #보통 float형 많이씀
arr_float.dtype

dtype('float64')

In [38]:
arr_str = np.array(["1","2","3"]) #str형은 잘안쓴다.
arr_str.dtype

dtype('<U1')

In [39]:
arr_int64 = arr_str.astype(np.int64) #int형으로 변환(astype). 문자가 a 이런거일경우 변형 x
arr_int64.dtype

dtype('int64')

In [40]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

In [41]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [42]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [43]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [44]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [45]:
arr1.dot(arr2) #행렬곱

array([[19, 22],
       [43, 50]])

In [46]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [48]:
arr= np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr_1 = arr[:2, 1:3] # ,기준 앞이 행 뒤가열이어서 슬라이싱 각각한 범위의 공통된 것을 뽑는다.
arr_1 #얘를 수정하면 원래 배열도 바뀌게 됨.

array([[2, 3],
       [5, 6]])

In [51]:
arr_1 = arr[:2, 1:3].copy() #얘는 원본배열이 같이 변경되지않음

In [52]:
arr[0,2] # 0행 2열 값 접근

3

In [54]:
arr[[0,1,2],[2,0,1]] #0행의 2열, 1행 0열, 2행 1열 뽑아냄

array([3, 4, 8])

In [55]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr>3 #3보다 큰값 찾아서 같은형태의 배열을 만들어줌(boolean 값 저장)
print(idx)

[[False False False]
 [ True  True  True]]


In [56]:
print(arr[idx]) #idx 를 통해 조건에 맞는 배열 구성

[4 5 6]


In [57]:
arr>3

array([[False, False, False],
       [ True,  True,  True]])

In [59]:
#조건에 해당하는 배열 가져오기
arr[arr>3]

array([4, 5, 6])

In [60]:
arr.sum() #전체 요소값 다 더해줌

21

In [61]:
arr.max() #전체 요소중 제일 큰 값

6

In [62]:
arr.max(axis=0) #값이 큰행을 가져오는건..가?

array([4, 5, 6])

In [63]:
arr.max(axis=1) #0행에서 가장큰수, 1행에서 가장 큰수

array([3, 6])

In [67]:
arr.sort()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
b = arr.copy();b

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
b[1,:]

array([4, 5, 6])

In [71]:
b.ravel() #1차원으로 풀어줌

array([1, 2, 3, 4, 5, 6])