In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [3]:
def main():
    enc = OneHotEncoder()
    sourcedata= [
        ['a'],
        ['b'],
        ['c']
    ]
    enc.fit(sourcedata)
    
    data=[
        ['a'],
        ['b'],
        ['c'],
        ['a'],
        ['b']
    ]
    print(enc.transform(data).toarray())

In [5]:
if __name__ == '__main__':
    main()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
